"""initial_clean_state

Revision ID: c0c2182be312
Revises: 
Create Date: 2025-07-27 09:07:14.406230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0c2182be312'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_envois_id', table_name='envois')
    op.drop_index('ix_envois_numero_dossier', table_name='envois')
    op.drop_table('envois')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('envois',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero_dossier', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_envoi', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('statut', postgresql.ENUM('EN_ATTENTE', 'ENVOYE', 'RECU', 'TRAITER', name='statutenvoi'), autoincrement=False, nullable=True),
    sa.Column('commentaire', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('service_technique_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_technique_id'], ['user.id'], name='envois_service_technique_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='envois_pkey')
    )
    op.create_index('ix_envois_numero_dossier', 'envois', ['numero_dossier'], unique=False)
    op.create_index('ix_envois_id', 'envois', ['id'], unique=False)
    # ### end Alembic commands ###
